// DO NOT EDIT: This file is generated by generateAst.ts
// To regenerate, run `yarn ast from the root directory`

import {Token} from './token';
import {LoxObject} from './types';

export abstract class Expr {
  static Binary = class Binary implements Expr {
    constructor(left: Expr, operator: Token, right: Expr) {
      this.left = left;
      this.operator = operator;
      this.right = right;
    }

    left: Expr;
    operator: Token;
    right: Expr;
  };

  static Grouping = class Grouping implements Expr {
    constructor(expression: Expr) {
      this.expression = expression;
    }

    expression: Expr;
  };

  static Literal = class Literal implements Expr {
    constructor(value: LoxObject) {
      this.value = value;
    }

    value: LoxObject;
  };

  static Unary = class Unary implements Expr {
    constructor(operator: Token, right: Expr) {
      this.operator = operator;
      this.right = right;
    }

    operator: Token;
    right: Expr;
  };
}
